version: '3'
services:
  # hazelcast imdg
  hazelcast:
    image: hazelcast/hazelcast
    volumes:
        - .:/cfg
    environment:
        - JAVA_OPTS=-Dhazelcast.config=/configFolder/hazelcast.xml -Dhazelcast.public.ip=127.0.0.1 -Dhazelcast.port=5555 -Dgroup.name=hz-compose -Dgroup.password=s3crEt -Dhazelcast.mancenter.url=http://localhost:8080/mancenter
    ports:
         - 5555:5701
    links:
        - "management-center:mancenter"
  # 2 hazelcast imdg
  hazelcast2:
    image: hazelcast/hazelcast  
    volumes:
        - .:/cfg
     environment:
        - JAVA_OPTS=-Dhazelcast.config=/configFolder/hazelcast.xml -Dhazelcast.public.ip=127.0.0.1 -Dhazelcast.port=5556 -Dgroup.name=hz-compose -Dgroup.password=s3crEt -Dhazelcast.mancenter.url=http://localhost:8080/mancenter
    ports:
         - 5556:5701
    links:
        - "management-center:mancenter"

  #management center
  management-center:
    image: hazelcast/management-center:latest
    # persisting mancenter users db folder to local disk
    volumes:
        - ~/mancenter3.9:/mancenter-3.9
    environment:
        - MANCENTER_DATA=/mancenter-3.9
        # enable REST interface on management center
        # http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Clustered_REST_via_Management_Center.html
        - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true
    ports:
        - 8080:8080
